### ISSUE TITLE
Use purescript-options?

### ISSUE THREAD

**Issue by paf31** [dbushenko/purescript-cookies#1]
`purescript-options` might be a good way to make the options object more type-safe.

**Comment by dbushenko** [comment]
@paf31 thanks for your advise, I'll look into the code today.

**Comment by andremarianiello** [comment]
Is this going to happen?

**Comment by dbushenko** [comment]
I never thought anyone uses this lib :-) Yes, I'll review and update the code to the new compiler and purescript-options.

**Comment by dbushenko** [comment]
@andremarianiello : please see the version 0.3.0.

**Comment by andremarianiello** [comment]
@dbushenko Thanks for doing this.
